TARGET=smon
CPP=/usr/bin/aarch64-unknown-linux-gnu-c++ 
AR=/usr/bin/aarch64-unknown-linux-gnu-ar

#CFLAGS=-g -std=c++14 -DBOOST_THREAD_USE_LIB -I ./Include -I ./MyUtilities/Include -pipe -O3 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard
CFLAGS_COMMON=-I ./Include -I ./MyUtilities/Include -I ./mruby/include -I ./OpenXLSX/OpenXLSX -I ./OpenXLSX/OpenXLSX/headers -I ./OpenXLSX/build/OpenXLSX -I ./OpenXLSX/Examples/external/nowide/include --input-charset=UTF-8 --exec-charset=UTF-8
LIBS_COMMON=-L ./MyUtilities -L OpenXLSX/build/output/ -lUtilities -lmruby -lOpenXLSX -llz4
#CFLAGS=-g $(CFLAGS_COMMON) -I ./mruby/build/host/include -pipe -O3 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard
CFLAGS=-g $(CFLAGS_COMMON) -I ./mruby/build/host/include -pipe -O3 -march=native
LIBS=-L ./mruby/build/host/lib $(LIBS_COMMON) -lboost_program_options -lboost_filesystem -lpthread
OBJS=Objects/linux-api.o Objects/qrcodegen.o Objects/default_options.o Objects/default_script.o
MAIN_DEPS=$(OBJS) MyUtilities/libUtilities.a mruby/build/host/lib/libmruby.a OpenXLSX/build/output/libOpenXLSX.a Objects
CPPFLAGS=-std=c++17 $(CFLAGS) -I QR-Code-generator/cpp/

all: $(Objects) $(TARGET)

clean:
	rm -rf $(TARGET) Objects/pre_smon Objects/*.[ao]

$(TARGET): Objects/main.o $(MAIN_DEPS) Objects/help.o
	$(CPP) $(CPPFLAGS) $< $(OBJS) Objects/help.o -o $@ $(LIBS)

Objects/pre_smon: Objects/main.o $(MAIN_DEPS) Objects/help_dummy.o
	$(CPP) $(CPPFLAGS) $< $(OBJS) Objects/help_dummy.o -o $@ $(LIBS)

Objects:
	mkdir -p Objects

document: Doxygen/html/index.html

Doxygen:
	mkdir -p Doxygen
Doxygen/html/index.html: Doxygen Doxyfile Source/main.cpp Source/linux-api.cpp Include/SerialControl.hpp Include/ComList.hpp Include/PipeList.hpp
	doxygen Doxyfile

mruby/build/host/lib/libmruby.a:
	/bin/bash build-mruby.sh
MyUtilities/libUtilities.a:
	/bin/bash build-MyUtilities.sh
OpenXLSX/build/output/libOpenXLSX.a:
	/bin/bash build-OpenXLSX.sh
QR-Code-generator/cpp/qrcodegen.cpp:
	/bin/bash build-QR-Code-generator.sh

Objects/%.o: Source/%.cpp
	$(CPP) $(CPPFLAGS) -c -o $@ $<
Objects/%.o: Source/%.c
	$(CPP) $(CFLAGS) -c -o $@ $<

Objects/main.o:                Source/main.cpp      Include/SerialControl.hpp MyUtilities/libUtilities.a mruby/build/host/lib/libmruby.a OpenXLSX/build/output/libOpenXLSX.a
Objects/linux-api.o:           Source/linux-api.cpp Include/SerialControl.hpp MyUtilities/libUtilities.a mruby/build/host/lib/libmruby.a OpenXLSX/build/output/libOpenXLSX.a
Objects/default_options.o:     Source/default_options.c
Objects/default_script.o:      Source/default_script.c
Source/default_options.c:      Source/default_options.rb mruby/build/host/lib/libmruby.a
	./mruby/bin/mrbc -Bdefault_options $<
Source/default_script.c:      Source/default_script.rb  mruby/build/host/lib/libmruby.a
	./mruby/bin/mrbc -Bdefault_script $<
Objects/qrcodegen.o: QR-Code-generator/cpp/qrcodegen.cpp
	$(CPP) $(CPPFLAGS) -c -o $@ $<
Objects/help.o: Source/help.s Source/help.txt.compress
	$(CPP) -c -Wa,--noexecstac -o $@ $<
Source/help.txt.compress: Source/help.txt test-script/test1.rb cmd.txt Objects/pre_smon
	cat cmd.txt | ./Objects/pre_smon
Objects/help_dummy.o: Source/help_dummy.s
	$(CPP) -c -Wa,--noexecstac -o $@ $<
